name: NordNights_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
- name: UpdateType
  type: string
  displayName: Update Type
  default: patch
  values:
  - patch
  - minor
  - major

trigger:
  branches:
    include:
      - master

variables:
- group: VSCE_PAT

pr:
  autoCancel: true
  branches:
    include:
      - master

steps:
  - pwsh: npm install vsce
    displayName: Install VSCE

  - pwsh: vsce publish -p $(VSCE_PAT) ${{ parameters.UpdateType }}
    displayName: Publish extension
